// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jkoqqcmcciziwhgumgap.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imprb3FxY21jY2l6aXdoZ3VtZ2FwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc2MTc4NTEsImV4cCI6MjA1MzE5Mzg1MX0.SeHCl7BB5GxprskQFTFWNy9D5Sa5ruMnBqQP_NbAS0s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);